name: baseimage-pr-notifier
on:
  pull_request_target:
    types: [opened]
jobs:
  baseimage-pr-notifier:
    runs-on: ubuntu-latest

    steps:
      - run: |
          if [[ "$PR_TITLE" =~ "Update base image" ]]; then
            curl -d '{"key":"builder-base image"}' -X POST $SLACK_WEBHOOK
          fi
          exit 0
        shell: bash
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
